### ISSUE TITLE
Cannot uninstall VPNMON-R3 From AMTM

### ISSUE THREAD

**Issue by Syked69** [ViktorJp/VPNMON-R3#13]
Hi,

Currently the script is stuck checking WAN connectivity and there's no way to show the operation menu to uninstall it. 

![Screenshot_20240514_151109_Termius](https://github.com/ViktorJp/VPNMON-R3/assets/58412219/fe74af7f-a0f1-464b-afa5-6acda44e4643)

**Comment by ViktorJp** [comment]
Sorry for the delay in response.  VPNMON-R3 needs to be able to get to 8.8.8.8 in order to perform the WAN check. If you can allow that traffic, it will be able to continue, and get out of this WAN down loop.

Should you wish to uninstall, you can always get to the setup menu using:

`sh vpnmon-r3.sh -setup`

**Comment by Syked69** [comment]
The WAN was up and functioning without any issues and there was nothing blocking access to DNS 8.8.8.8. In fact this is the DNS I use on my router WAN configuration and was working fine and could access the internet.

I have managed to uninstall it. Thanks.

15 May 2024 5:34:02 am ViktorJp ***@***.***>:

**Comment by ViktorJp** [comment]
It checks for WAN connectivity by creating an SSL handshake with 8.8.8.8... if it wasn't able to complete this step, there's clearly something wrong.  Couple of questions... What model router you running?  What version of Asus-Merlin is on there?  Did VPNMON-R3 work before, or did it not work straight out of the gate?  Are you running any Dual-WAN configuration?  Any other particular scripts in use?  Thanks in advance.

**Comment by Syked69** [comment]
See below for my responses.

What model router you running? *ASUS **RT-AC88U*

What version of Asus-Merlin is on there? *386.13*

Did VPNMON-R3 work before, or did it not work straight out of the gate? *It worked once then didn't work again after reboot*

Are you running any Dual-WAN configuration? *No*

Any other particular scripts in use?

Diversion                  5.1.3
Skynet                     7.5.9
MerlinAU                   1.1.2
connmon                    3.0.2
uiDivStats                 4.0.0

Also wanted to point out that I have DNSoverTLS enabled.

15 May 2024 12:05:39 pm ViktorJp ***@***.***>:

**Comment by ViktorJp** [comment]
Thanks... Not seeing anything that could interfere. Not much to suggest without jumping into serious debugging on your end to figure out a cause. I'm running both on a GT-AX6000 AND RT-AX88U without issue, and not heard of any other reports... other than those few who were blocking 8.8.8.8.  

I'm planning on offering an option to allow user input  toswitch this to a server of your own choice, and have it on my to-do list.
